### Create Office Session
POST http://localhost:4567/api/v1/sessions/office
Content-Type: application/json

###

### Get WebSocket Connection Info
GET http://localhost:4567/api/v1/sessions/{{connection_id}}/connect

###

### Stop Session and Delete Pod
DELETE http://localhost:4567/sessions/{{connection_id}}/stop

###

### List Active Sessions
GET http://localhost:4567/sessions/

###

### Create Browser Pod
POST http://localhost:4567/api/v1/pods/browser
Content-Type: application/json

###

### Create Office Pod (alternate)
POST http://localhost:4567/api/v1/pods/office
Content-Type: application/json
