// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEmailUser(ctx context.Context, arg CreateEmailUserParams) (User, error)
	CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error)
	// Session management queries
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, sessionToken string) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	GetSession(ctx context.Context, sessionToken string) (GetSessionRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	// Email verification queries
	GetUserByEmailVerificationToken(ctx context.Context, dollar_1 string) (User, error)
	GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error)
	ListUsers(ctx context.Context) ([]User, error)
	ResendEmailVerification(ctx context.Context, arg ResendEmailVerificationParams) (User, error)
	UpdateEmailVerificationToken(ctx context.Context, arg UpdateEmailVerificationTokenParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	// Profile and settings management queries
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error)
	VerifyUserEmail(ctx context.Context, dollar_1 string) (User, error)
}

var _ Querier = (*Queries)(nil)
