apiVersion: batch/v1
kind: CronJob
metadata:
  name: browser-sandbox-cleanup
  namespace: browser-sandbox
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: browser-sandbox-cleanup
          containers:
          - name: cleanup
            image: ghcr.io/browsersec/kubebrowse-cleanup:chore-improve-back
            env:
            - name: CLEANUP_NAMESPACE
              value: "browser-sandbox"
            - name: CLEANUP_GRACE_PERIOD
              value: "5m"
            - name: CLEANUP_CRON_SCHEDULE
              value: "*/5 * * * *"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: browser-sandbox-cleanup
  namespace: browser-sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: browser-sandbox
  name: browser-sandbox-cleanup
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: browser-sandbox-cleanup
  namespace: browser-sandbox
subjects:
- kind: ServiceAccount
  name: browser-sandbox-cleanup
  namespace: browser-sandbox
roleRef:
  kind: Role
  name: browser-sandbox-cleanup
  apiGroup: rbac.authorization.k8s.io
