# Backend API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubebrowse.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubebrowse.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "kubebrowse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "kubebrowse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
      annotations:
        {{- toYaml .Values.api.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubebrowse.serviceAccountName" . }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: {{ .Values.api.service.port | default 4567 }}
              name: api
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          env:
            - name: GUACD_ADDRESS
              value: "{{ .Values.guacd.service.name | default "guacd" }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.guacd.service.port | default 4822 }}"
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.service.name | default "postgres" }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.service.port | default 5432 | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName | default "postgres-secret" }}
                  key: {{ .Values.postgres.secretKeys.username | default "username" }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName | default "postgres-secret" }}
                  key: {{ .Values.postgres.secretKeys.password | default "password" }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbName | default "sandbox_db" }}
            - name: REDIS_HOST
              value: "{{ .Values.redis.service.name | default "redis" }}.{{ .Release.Namespace }}.svc.cluster.local"
            - name: REDIS_PORT
              value: {{ .Values.redis.service.port | default 6379 | quote }}
            - name: MINIO_ENDPOINT
              value: "{{ .Values.minio.service.name | default "minio" }}:{{ .Values.minio.service.port | default 9000 }}"
            - name: MINIO_ACCESS_KEY # Or MINIO_ROOT_USER based on MinIO config
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName | default "minio-secret" }}
                  key: {{ .Values.minio.secretKeys.accessKey | default "rootUser" }} # Adjust default if using accesskey
            - name: MINIO_SECRET_KEY # Or MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName | default "minio-secret" }}
                  key: {{ .Values.minio.secretKeys.secretKey | default "rootPassword" }} # Adjust default if using secretkey
            - name: MINIO_BUCKET
              value: {{ .Values.minio.bucketName | default "browser-sandbox" }}
            - name: CLAMAV_ADDRESS
              value: {{ .Values.clamav.address | default (printf "http://clamd-api.%s.svc.cluster.local:3000" .Release.Namespace) }}
            - name: KUBERNETES_NAMESPACE
              value: {{ .Release.Namespace }}
            {{- range .Values.api.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
