# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubebrowse.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubebrowse.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: {{ .Values.redis.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "kubebrowse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "kubebrowse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      serviceAccountName: {{ include "kubebrowse.serviceAccountName" . }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag | default "alpine" }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.redis.service.port | default 6379 }}
              name: redis
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
